[package]
name = "myhealth"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.13", default-features = false, features = ["macros", "rustls", "ctrlc_handler"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
chrono = "0"
anyhow = "1"
clap = { version = "4", features = ["derive"] }